### ISSUE TITLE
UX: "Connecting to app" Screen

### ISSUE THREAD

**Issue by swissmanu** [mweibel/esrscan#1]
I was a little confused what to do upon the first app start when the "Connecting to app" screen was displayed.
Should i press next? Will something happen automagically?

Since you told me the app continues looking desktop apps up in background anyway, I suggest something less obtrusive than this screen.
Maybe you can do something with an overlay message upon connect and/or disconnect?

![Overlay](http://i.imgur.com/2zhIcD4.png)

**Comment by mweibel** [comment]
Is a good idea. One reason for having a separate screen is: in the same network there could be multiple desktop apps and you probably want to select which one to connect to. But maybe this could be handled separately as well.
